default: &default
    adapter: mysql2
    encoding: utf8mb4
    socket: /var/run/mysqld/mysqld.sock

development:
    <<: *default
    database: blog_development
    url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

test:
    <<: *default
    database: blog_test
    url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

production:
    <<: *default
    database: blog_production
    url: <%= ENV['DATABASE_URL'] %>
