default: &default
  adapter: mysql2
  encoding: utf8mb4
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: shop_development
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

test:
  <<: *default
  database: shop_test
  url: <%= ENV['DEVELOPMENT_DATABASE_URL'] %>

production:
  <<: *default
  database: shop_production
  url: <%= ENV['DATABASE_URL'] %>
